//                                                   
//  kern_resources.hpp                               
//  WhateverGreen                                    
//                                                   
//  Copyright © 2018 vit9696. All rights reserved.   
//                                                   
//  This is an autogenerated file!                   
//  Please avoid any modifications!                  
//                                                   

#include <Headers/kern_user.hpp>                     
#include <stdint.h>                                  

extern UserPatcher::BinaryModInfo ADDPR(binaryMod)[];
extern const size_t ADDPR(binaryModSize);            

extern UserPatcher::ProcInfo ADDPR(procInfoModern)[];
extern const size_t ADDPR(procInfoModernSize);       

extern UserPatcher::ProcInfo ADDPR(procInfoLegacy)[];
extern const size_t ADDPR(procInfoLegacySize);       


// Section list

enum : uint32_t {
	SectionUnused = 0,
	SectionLEGACYHWDRMID = 1,
	SectionEXTSLOTS = 2,
	SectionHWDRMID = 3,
	SectionOFFLINE = 4,
	SectionFCPUID = 5,
	SectionBGRA = 6,
	SectionNDRMI = 7,
	SectionBOARDID = 8,
	SectionWHITELIST = 9,
	SectionCOMPATRENDERER = 10,
	SectionNSTREAM = 11,
	SectionLEGACYSWDRMID = 12,
};
