//                                                   
//  kern_resources.cpp                               
//  WhateverGreen                                    
//                                                   
//  Copyright © 2018 vit9696. All rights reserved.   
//                                                   
//  This is an autogenerated file!                   
//  Please avoid any modifications!                  
//                                                   

#include "kern_resources.hpp"                      


// Patch section

alignas(8) static const uint8_t patchBuf0[] { 0xBF, 0x69, 0x6D, 0x72, 0x64, 0xBE, 0x2C, 0x01, 0x00, 0x00, };
alignas(8) static const uint8_t patchBuf1[] { 0xBF, 0x6E, 0x6D, 0x72, 0x64, 0xBE, 0x2C, 0x01, 0x00, 0x00, };
alignas(8) static const uint8_t patchBuf2[] { 0xBF, 0x69, 0x6D, 0x72, 0x64, 0xBE, 0x90, 0x01, 0x00, 0x00, };
alignas(8) static const uint8_t patchBuf3[] { 0xBF, 0x6E, 0x6D, 0x72, 0x64, 0xBE, 0x90, 0x01, 0x00, 0x00, };
alignas(8) static const uint8_t patchBuf4[] { 0x4D, 0x61, 0x63, 0x50, 0x72, 0x6F, 0x35, 0x2C, 0x31, 0x00, 0x4D, 0x61, 0x63, 0x50, 0x72, 0x6F, 0x36, 0x2C, 0x31, 0x00, };
alignas(8) static const uint8_t patchBuf5[] { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, };
static UserPatcher::BinaryModPatch patches0[] {
	{ CPU_TYPE_X86_64, 0, patchBuf0, patchBuf1, 10, 0, 1, UserPatcher::FileSegment::SegmentTextText, SectionNDRMI },
	{ CPU_TYPE_X86_64, 0, patchBuf2, patchBuf3, 10, 0, 1, UserPatcher::FileSegment::SegmentTextText, SectionNDRMI },
	{ CPU_TYPE_X86_64, 0, patchBuf4, patchBuf5, 20, 0, 1, UserPatcher::FileSegment::SegmentTextCstring, SectionEXTSLOTS },
};
alignas(8) static const uint8_t patchBuf6[] { 0x01, 0x00, 0x00, 0x00, 0x0F, 0xA2, };
alignas(8) static const uint8_t patchBuf7[] { 0xC2, 0x06, 0x02, 0x00, 0x90, 0x90, };
static UserPatcher::BinaryModPatch patches1[] {
	{ CPU_TYPE_X86_64, 0, patchBuf6, patchBuf7, 6, 0, 1, UserPatcher::FileSegment::SegmentTextText, SectionFCPUID },
};
alignas(8) static const uint8_t patchBuf8[] { 0xC7, 0xC0, 0x01, 0x00, 0x00, 0x00, 0x0F, 0xA2, };
alignas(8) static const uint8_t patchBuf9[] { 0xC7, 0xC0, 0xC3, 0x06, 0x03, 0x00, 0x90, 0x90, };
alignas(8) static const uint8_t patchBuf10[] { 0xC7, 0xC0, 0x01, 0x00, 0x00, 0x00, 0x0F, 0xA2, };
alignas(8) static const uint8_t patchBuf11[] { 0xC7, 0xC0, 0xC2, 0x06, 0x02, 0x00, 0x90, 0x90, };
static UserPatcher::BinaryModPatch patches2[] {
	{ CPU_TYPE_X86_64, 0, patchBuf8, patchBuf9, 8, 0, 5, UserPatcher::FileSegment::SegmentTextText, SectionLEGACYHWDRMID },
	{ CPU_TYPE_X86_64, 0, patchBuf10, patchBuf11, 8, 0, 5, UserPatcher::FileSegment::SegmentTextText, SectionLEGACYSWDRMID },
};
alignas(8) static const uint8_t patchBuf12[] { 0xC7, 0xC0, 0x01, 0x00, 0x00, 0x00, 0x0F, 0xA2, };
alignas(8) static const uint8_t patchBuf13[] { 0xC7, 0xC0, 0xC3, 0x06, 0x03, 0x00, 0x90, 0x90, };
alignas(8) static const uint8_t patchBuf14[] { 0xC7, 0xC0, 0x01, 0x00, 0x00, 0x00, 0x0F, 0xA2, };
alignas(8) static const uint8_t patchBuf15[] { 0xC7, 0xC0, 0xC2, 0x06, 0x02, 0x00, 0x90, 0x90, };
static UserPatcher::BinaryModPatch patches3[] {
	{ CPU_TYPE_X86_64, 0, patchBuf12, patchBuf13, 8, 0, 2, UserPatcher::FileSegment::SegmentTextText, SectionLEGACYHWDRMID },
	{ CPU_TYPE_X86_64, 0, patchBuf14, patchBuf15, 8, 0, 2, UserPatcher::FileSegment::SegmentTextText, SectionLEGACYSWDRMID },
};
alignas(8) static const uint8_t patchBuf16[] { 0x66, 0x6F, 0x72, 0x63, 0x65, 0x4F, 0x66, 0x66, };
alignas(8) static const uint8_t patchBuf17[] { 0x61, 0x76, 0x6F, 0x69, 0x64, 0x4F, 0x66, 0x66, };
alignas(8) static const uint8_t patchBuf18[] { 0x68, 0x77, 0x65, 0x42, 0x47, 0x52, 0x41, };
alignas(8) static const uint8_t patchBuf19[] { 0x73, 0x77, 0x65, 0x42, 0x47, 0x52, 0x41, };
alignas(8) static const uint8_t patchBuf20[] { 0x00, };
alignas(8) static const uint8_t patchBuf21[] { 0x00, };
alignas(8) static const uint8_t patchBuf22[] { 0x62, 0x6F, 0x61, 0x72, 0x64, 0x2D, 0x69, 0x64, 0x00, };
alignas(8) static const uint8_t patchBuf23[] { 0x73, 0x68, 0x69, 0x6B, 0x69, 0x2D, 0x69, 0x64, 0x00, };
alignas(8) static const uint8_t patchBuf24[] { 0x62, 0x6F, 0x61, 0x72, 0x64, 0x2D, 0x69, 0x64, 0x00, };
alignas(8) static const uint8_t patchBuf25[] { 0x68, 0x77, 0x64, 0x72, 0x6D, 0x2D, 0x69, 0x64, 0x00, };
static UserPatcher::BinaryModPatch patches4[] {
	{ CPU_TYPE_X86_64, 0, patchBuf16, patchBuf17, 8, 0, 1, UserPatcher::FileSegment::SegmentTextCstring, SectionOFFLINE },
	{ CPU_TYPE_X86_64, 0, patchBuf18, patchBuf19, 7, 0, 1, UserPatcher::FileSegment::SegmentTextCstring, SectionBGRA },
	{ CPU_TYPE_X86_64, 0, patchBuf20, patchBuf21, 1, 0, 1, UserPatcher::FileSegment::SegmentTextText, SectionCOMPATRENDERER },
	{ CPU_TYPE_X86_64, 0, patchBuf22, patchBuf23, 9, 0, 1, UserPatcher::FileSegment::SegmentTextCstring, SectionBOARDID },
	{ CPU_TYPE_X86_64, UserPatcher::BinaryModPatchFlags::LocalOnly, patchBuf24, patchBuf25, 9, 0, 1, UserPatcher::FileSegment::SegmentTextCstring, SectionHWDRMID },
};
alignas(8) static const uint8_t patchBuf26[] { 0x62, 0x6F, 0x61, 0x72, 0x64, 0x2D, 0x69, 0x64, 0x00, };
alignas(8) static const uint8_t patchBuf27[] { 0x73, 0x68, 0x69, 0x6B, 0x69, 0x2D, 0x69, 0x64, 0x00, };
static UserPatcher::BinaryModPatch patches5[] {
	{ CPU_TYPE_X86_64, 0, patchBuf26, patchBuf27, 9, 0, 1, UserPatcher::FileSegment::SegmentTextCstring, SectionBOARDID },
};

// Mod section

UserPatcher::BinaryModInfo ADDPR(binaryMod)[] {
	{ "/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox", patches0, 3 },
	{ "/System/Library/PrivateFrameworks/CoreFP.framework/Versions/A/CoreFP", patches1, 1 },
	{ "/System/Library/PrivateFrameworks/CoreLSKD.framework/Versions/A/CoreLSKD", patches2, 2 },
	{ "/System/Library/PrivateFrameworks/CoreLSKDMSE.framework/Versions/A/CoreLSKDMSE", patches3, 2 },
	{ "/System/Library/PrivateFrameworks/AppleGVA.framework/Versions/A/AppleGVA", patches4, 5 },
	{ "/System/Library/PrivateFrameworks/AppleVPA.framework/Versions/A/AppleVPA", patches5, 1 },
};

const size_t ADDPR(binaryModSize) {6};

// Process list
using PF = UserPatcher::ProcInfo::ProcFlags;

UserPatcher::ProcInfo ADDPR(procInfoLegacy)[] {
	{ "/Applications/iTunes.app/Contents/MacOS/iTunes", 46, SectionNDRMI, PF::MatchExact },
	{ "/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player", 66, SectionNDRMI, PF::MatchExact },
	{ "/System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent", 141, SectionWHITELIST, PF::MatchExact },
	{ "/Applications/Safari.app/Contents/MacOS/Safari", 46, SectionWHITELIST, PF::MatchExact },
	{ "/System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService", 131, SectionWHITELIST, PF::MatchExact },
	{ "/Final Cut Pro.app/Contents/MacOS/Final Cut Pro", 47, SectionWHITELIST, PF::MatchSuffix },
	{ "/Motion.app/Contents/MacOS/Motion", 33, SectionWHITELIST, PF::MatchSuffix },
	{ "/Compressor.app/Contents/MacOS/Compressor", 41, SectionWHITELIST, PF::MatchSuffix },
	{ "/IINA.app/Contents/MacOS/IINA", 29, SectionWHITELIST, PF::MatchSuffix },
	{ "/VLC.app/Contents/MacOS/VLC", 27, SectionWHITELIST, PF::MatchSuffix },
	{ "/MacX Video Converter Pro.app/Contents/MacOS/MacX Video Converter Pro", 69, SectionWHITELIST, PF::MatchSuffix },
	{ "/XviD4PSP.app/Contents/MacOS/XviD4PSP", 37, SectionWHITELIST, PF::MatchSuffix },
	{ "/Opera.app/Contents/MacOS/Opera", 31, SectionWHITELIST, PF::MatchSuffix },
	{ "/Firefox.app/Contents/MacOS/firefox", 35, SectionWHITELIST, PF::MatchAny },
	{ "/Slack.app/Contents/MacOS/Slack", 31, SectionWHITELIST, PF::MatchSuffix },
	{ "/Visual Studio Code.app/Contents/MacOS/Electron", 47, SectionWHITELIST, PF::MatchSuffix },
	{ "/Google Chrome.app/Contents/MacOS/Google Chrome", 47, SectionWHITELIST, PF::MatchSuffix },
	{ "/VDADecoderChecker", 18, SectionWHITELIST, PF::MatchSuffix },
	{ "/DaVinci Resolve.app/Contents/MacOS/Resolve", 43, SectionWHITELIST, PF::MatchSuffix },
	{ "/mpv", 4, SectionWHITELIST, PF::MatchSuffix },
	{ "/ffmpeg", 7, SectionWHITELIST, PF::MatchSuffix },
	{ "/Applications/FaceTime.app/Contents/MacOS/FaceTime", 50, SectionWHITELIST, PF::MatchExact },
	{ "/Applications/Photos.app/Contents/MacOS/Photos", 46, SectionWHITELIST, PF::MatchExact },
	{ "/System/Library/CoreServices/cloudphotosd.app/Contents/MacOS/cloudphotosd", 73, SectionWHITELIST, PF::MatchExact },
	{ "/System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/XPCServices/QuickLookUIService.xpc/Contents/MacOS/QuickLookUIService", 167, SectionWHITELIST, PF::MatchExact },
	{ "/usr/libexec/AirPlayXPCHelper", 29, SectionWHITELIST, PF::MatchExact },
	{ "/Live Screen Capture.app/Contents/MacOS/Live Screen Capture", 59, SectionWHITELIST, PF::MatchSuffix },
	{ "/iMovie.app/Contents/MacOS/iMovie", 33, SectionWHITELIST, PF::MatchSuffix },
	{ "/Photo Booth.app/Contents/MacOS/Photo Booth", 43, SectionWHITELIST, PF::MatchSuffix },
	{ "/Applications/iTunes.app/Contents/MacOS/iTunes", 46, SectionHWDRMID, PF::MatchExact },
	{ "/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player", 66, SectionHWDRMID, PF::MatchExact },
	{ "/System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent", 141, SectionNSTREAM, PF::MatchExact },
};

const size_t ADDPR(procInfoLegacySize) {32};
// Process list
using PF = UserPatcher::ProcInfo::ProcFlags;

UserPatcher::ProcInfo ADDPR(procInfoModern)[] {
	{ "/System/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player", 73, SectionNDRMI, PF::MatchExact },
	{ "/System/Applications/TV.app/Contents/MacOS/TV", 45, SectionNDRMI, PF::MatchExact },
	{ "/System/Applications/Music.app/Contents/MacOS/Music", 51, SectionNDRMI, PF::MatchExact },
	{ "/System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent", 141, SectionWHITELIST, PF::MatchExact },
	{ "/System/Applications/Safari.app/Contents/MacOS/Safari", 53, SectionWHITELIST, PF::MatchExact },
	{ "/System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService", 131, SectionWHITELIST, PF::MatchExact },
	{ "/Final Cut Pro.app/Contents/MacOS/Final Cut Pro", 47, SectionWHITELIST, PF::MatchSuffix },
	{ "/Motion.app/Contents/MacOS/Motion", 33, SectionWHITELIST, PF::MatchSuffix },
	{ "/Compressor.app/Contents/MacOS/Compressor", 41, SectionWHITELIST, PF::MatchSuffix },
	{ "/IINA.app/Contents/MacOS/IINA", 29, SectionWHITELIST, PF::MatchSuffix },
	{ "/VLC.app/Contents/MacOS/VLC", 27, SectionWHITELIST, PF::MatchSuffix },
	{ "/MacX Video Converter Pro.app/Contents/MacOS/MacX Video Converter Pro", 69, SectionWHITELIST, PF::MatchSuffix },
	{ "/XviD4PSP.app/Contents/MacOS/XviD4PSP", 37, SectionWHITELIST, PF::MatchSuffix },
	{ "/Opera.app/Contents/MacOS/Opera", 31, SectionWHITELIST, PF::MatchSuffix },
	{ "/Firefox.app/Contents/MacOS/firefox", 35, SectionWHITELIST, PF::MatchAny },
	{ "/Slack.app/Contents/MacOS/Slack", 31, SectionWHITELIST, PF::MatchSuffix },
	{ "/Visual Studio Code.app/Contents/MacOS/Electron", 47, SectionWHITELIST, PF::MatchSuffix },
	{ "/Google Chrome.app/Contents/MacOS/Google Chrome", 47, SectionWHITELIST, PF::MatchSuffix },
	{ "/VDADecoderChecker", 18, SectionWHITELIST, PF::MatchSuffix },
	{ "/DaVinci Resolve.app/Contents/MacOS/Resolve", 43, SectionWHITELIST, PF::MatchSuffix },
	{ "/mpv", 4, SectionWHITELIST, PF::MatchSuffix },
	{ "/ffmpeg", 7, SectionWHITELIST, PF::MatchSuffix },
	{ "/System/Applications/FaceTime.app/Contents/MacOS/FaceTime", 57, SectionWHITELIST, PF::MatchExact },
	{ "/System/Applications/Photos.app/Contents/MacOS/Photos", 53, SectionWHITELIST, PF::MatchExact },
	{ "/System/Library/CoreServices/cloudphotosd.app/Contents/MacOS/cloudphotosd", 73, SectionWHITELIST, PF::MatchExact },
	{ "/System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/XPCServices/QuickLookUIService.xpc/Contents/MacOS/QuickLookUIService", 167, SectionWHITELIST, PF::MatchExact },
	{ "/usr/libexec/AirPlayXPCHelper", 29, SectionWHITELIST, PF::MatchExact },
	{ "/Live Screen Capture.app/Contents/MacOS/Live Screen Capture", 59, SectionWHITELIST, PF::MatchSuffix },
	{ "/iMovie.app/Contents/MacOS/iMovie", 33, SectionWHITELIST, PF::MatchSuffix },
	{ "/Photo Booth.app/Contents/MacOS/Photo Booth", 43, SectionWHITELIST, PF::MatchSuffix },
	{ "/System/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player", 73, SectionHWDRMID, PF::MatchExact },
	{ "/System/Applications/TV.app/Contents/MacOS/TV", 45, SectionHWDRMID, PF::MatchExact },
	{ "/System/Applications/Music.app/Contents/MacOS/Music", 51, SectionHWDRMID, PF::MatchExact },
	{ "/System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent", 141, SectionNSTREAM, PF::MatchExact },
};

const size_t ADDPR(procInfoModernSize) {34};